apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helloworldservice }}
  namespace: {{ .Values.devnamespace }}
spec:
  selector:
    app: {{ .Values.helloApplicationName }}
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
      
  